### ISSUE TITLE
Only for July 2018 I have this problem. Type of card: MIR (VISA is OK)

### ISSUE THREAD

**Issue by mobile-systems** [gerasiov/ofxstatement-russian#7]
~/ofx$ ofxstatement convert -t sberbank 36160_Jul18.txt 36160_Jul18.ofx
Traceback (most recent call last):
  File "/usr/bin/ofxstatement", line 11, in <module>
    load_entry_point('ofxstatement==0.6.0', 'console_scripts', 'ofxstatement')()
  File "/usr/lib/python3/dist-packages/ofxstatement/tool.py", line 150, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/ofxstatement/tool.py", line 128, in convert
    statement = parser.parse()
  File "/usr/lib/python3/dist-packages/ofxstatement/plugins/sberbank.py", line 181, in parse
    self.run(line)
  File "/usr/lib/python3/dist-packages/ofxstatement/plugins/sberbank.py", line 174, in run
    nextState = self.machine[self.currentState].run(line)
  File "/usr/lib/python3/dist-packages/ofxstatement/plugins/sberbank.py", line 44, in run
    function(match)
  File "/usr/lib/python3/dist-packages/ofxstatement/plugins/sberbank.py", line 125, in extractTransactionAppend
    self.transaction.memo += second.strip()
AttributeError: 'NoneType' object has no attribute 'memo'

**Comment by gerasiov** [comment]
Could you please provide sample file to reproduce the problem?
(Better if you replace sensitive info with something non-meaningful, but the same length and character class.)

**Comment by mobile-systems** [comment]
Sorry, I sent example to private email


> Could you please provide sample file to reproduce the problem?
> (Better if you replace sensitive info with something non-meaningful, but the same length and character class.)

**Comment by gerasiov** [comment]
Looks like version from master works ok with your file.
